name: LotusChat
version: ${project.version}
main: com.nygmatic.core.lotuschat.LotusChat
api-version: 1.13
authors: [Nygmatic]
description: Scuffed chat plugin made by yours truly, dat boi

commands:
  createchannel:
    description: Command to create new channels
    usage: /<command> <symbol> <prefix> <send_permission> <receive_permission> <radius>
  namechange:
    description: Command to change players' first or last name
    usage: /<command> <first/last> <new_name> (player_username)